name: test2

on:
  push:
    branches:
      - "test2"
  pull_request:
    branches:
      - "main" 
    paths:
      - ".github/workflows/test2.yaml"

jobs:
  release-front-end-assets:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - run: npm ci
    - run: npm test
    - run: npm run lint